#before_script:
#  - apt-get update -qq && apt-get install -y -qq pandoc
image: node:12.16.3
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install hexo-cli -g
    - npm install
    - hexo -v
    - hexo g #生成静态文件
    - hexo d #部署
  artifacts:
    paths:
      - public
  only:
    - master